# Generated by Django 4.2.5 on 2023-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField(default=0, help_text='in mintues')),
                ('difficulty', models.CharField(max_length=13)),
                ('ingredients', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
