# Generated by Django 4.2.5 on 2023-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pictures',
            field=models.ImageField(default='no_picture.jpg', upload_to='recipes'),
        ),
    ]
